---
- name: Nextcloud install packages
  apt:
    name: "{{ nextcloud__default_packages }}"
    update_cache: yes
    state: present
  when: nextcloud__install

# for pdlib, check https://help.nextcloud.com/t/how-to-install-pdlib-on-your-server-for-face-recognition/167979 
- name: Add pdlib package key
  apt_key:
    url: https://repo.delellis.com.ar/repo.gpg.key
    keyring: /etc/apt/trusted.gpg.d/delellis-keyring.gpg
  when:
    - nextcloud__install
    - nextcloud__add_pdlib is defined and nextcloud__add_pdlib

- name: Add pdlib repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/delellis-keyring.gpg arch=amd64] https://repo.delellis.com.ar bullseye bullseye
    state: present
    filename: delellis
  when:
    - nextcloud__install
    - nextcloud__add_pdlib is defined and nextcloud__add_pdlib

- name: Nextcloud Face recog install packages
  apt:
    name: php7.4-pdlib
    update_cache: yes
    state: present
  when:
    - nextcloud__install
    - nextcloud__add_pdlib is defined and nextcloud__add_pdlib

- name: Apache2 PHP configuration file 1/4
  lineinfile:
    path: "{{ nextcloud__apache_php_config_file }}"
    regexp: "^memory_limit = "
    line: "memory_limit = {{ nextcloud__apache_memory_limit }}"
  when: nextcloud__configure
  notify: Reload Apache2

- name: Apache2 PHP configuration file 2/4
  lineinfile:
    path: "{{ nextcloud__apache_php_config_file }}"
    regexp: "^upload_max_filesize = "
    line: "upload_max_filesize = {{ nextcloud__apache_upload_max_filesize }}"
  when: nextcloud__configure
  notify: Reload Apache2

- name: Apache2 PHP configuration file 3/4
  lineinfile:
    path: "{{ nextcloud__apache_php_config_file }}"
    regexp: "^post_max_size = "
    line: "post_max_size = {{ nextcloud__apache_post_max_size }}"
  when: nextcloud__configure
  notify: Reload Apache2

- name: Apache2 PHP configuration file 4/4
  lineinfile:
    path: "{{ nextcloud__apache_php_config_file }}"
    regexp: "^max_execution_time = "
    line: "max_execution_time = {{ nextcloud__apache_max_execution_time }}"
  when: nextcloud__configure
  notify: Reload Apache2

- name: Create MariaDB Database
  mysql_db:
    name: "{{ nextcloud__db_name }}"
    state: present
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock
  when: nextcloud__configure

- name: Create database user
  mysql_user:
    config_file: "/etc/mysql/debian.cnf"
    name: "{{ nextcloud__db_user }}"
    host: localhost
    password: "{{ nextcloud__db_pass }}"
    priv: '{{ nextcloud__db_name }}.*:ALL'
    state: present
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock
  when: nextcloud__configure

- name: Verify if archive is present
  stat:
    path: /var/www/html/nextcloud
  register: nextcloud_downloaded
  check_mode: no

- name: Download and Unarchive downloaded
  unarchive:
    src: "{{ nextcloud__download_url }}"
    dest: /var/www/html
    owner: www-data
    group: www-data
    remote_src: yes
  when:
    - nextcloud__configure
    - not nextcloud_downloaded.stat.exists

- name: Configure apache modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - rewrite
    - headers
    - env
    - dir
    - mime
    - ssl
  when: nextcloud__configure
  notify: Restart Apache2

- name: Configure apache server virtualhost
  template:
    src: nextcloud_apache.conf
    dest: /etc/apache2/sites-available/nextcloud.conf
  when: nextcloud__configure
  notify: Restart Apache2

- name: Setup symlink for enabling site
  file:
    state: link
    path: /etc/apache2/sites-enabled/nextcloud.conf
    src: /etc/apache2/sites-available/nextcloud.conf
  when: nextcloud__configure
  notify: Restart Apache2

- name: Create index for NextCloud Fulltextsearch
  shell: 'curl -X PUT "{{ nextcloud__fulltextsearch_es_host }}:9200/{{ nextcloud__fulltextsearch_es_index }}?pretty"'
  when:
    - nextcloud__configure
    - nextcloud__fulltextsearch

- name: Create processor for NextCloud
  shell: 'curl -X PUT -d ''{"description" : "Extract attachment information",  "processors" : [{"attachment" : {"field" : "content","indexed_chars" : -1}}]}'' -H "Content-Type: application/json" "{{ nextcloud__fulltextsearch_es_host }}:9200/_ingest/pipeline/attachment?pretty"'
  when:
    - nextcloud__configure
    - nextcloud__fulltextsearch

- name: Create service file for live indexing
  template:
    src: nextcloud-fulltext-elasticsearch-worker.service
    dest: /etc/systemd/system/nextcloud-fulltext-elasticsearch-worker.service
  when:
    - nextcloud__configure
    - nextcloud__fulltextsearch

- name: Enable live indexing
  service:
    name: nextcloud-fulltext-elasticsearch-worker
    state: enabled
  when:
    - nextcloud__configure
    - nextcloud__fulltextsearch

# First indexation should be done before starting this service
# It's done with: #sudo -u www-data nice -19 php /var/www/html/nextcloud/occ fulltextsearch:index
- name: Start live indexing
  service:
    name: nextcloud-fulltext-elasticsearch-worker
    state: started
  when:
    - nextcloud__configure
    - nextcloud__fulltextsearch
    - nextcloud__fulltextsearch_initial_indexed
